template_dir = "template.inp"
#scratch = "/gpfs/scratch/kaifzheng/FEFF"
scratch = "/gpfs/scratch/kaifzheng/FEFF"
CA = "Pt"
radius = 14
mode = "seq_multi"
cores = 1
tasks = 40
site = [0]
pos_filename = ""
average = true
file_type="*.xyz"
symmetry=true
restart=false
#site_rule="site=int(readfiles[i].split('.')[0].split('site_')[1])"
